# Netlify Build & Redirect Configuration

[build]
  command = "npm run build" # The command to build your site
  publish = "dist"          # The directory that contains the built site

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
